# Generated by Django 5.1 on 2024-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
        migrations.AddField(
            model_name='person',
            name='game_plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wines',
            field=models.IntegerField(default=0),
        ),
    ]
