# Generated by Django 5.1 on 2024-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_person_date_person_game_plays_person_losses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
