services:
  setup_elk:
    build:
      context: ./setup
    image: setup_elk
    container_name: setup_elk
    volumes:
      - ./certs:/certs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      discovery.type: single-node # using for single node
      ES_JAVA_OPTS: -Xms512m -Xmx512m # set JVM heap size for reduce momory usage
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:?error} # define password
      xpack.security.enabled: true # authetication username is elastic
      xpack.security.http.ssl.enabled: true
      xpack.security.http.ssl.key: certs/elasticsearch-key.pem
      xpack.security.http.ssl.certificate: certs/elasticsearch.pem
      xpack.security.http.ssl.certificate_authorities: certs/root-ca.pem
    mem_limit: ${MEM_LIMIT}
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
    depends_on:
      - setup_elk
    # networks:
    #   - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: logstash
    environment:
      ELASTIC_PASSWORD:
    # command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./certs:/usr/share/logstash/config/certs
      # - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      # - ./logstash/ingest_data/:/usr/share/logstash/ingestdata/
    mem_limit: ${MEM_LIMIT}
    ports:
      - 5044:5044
    # networks:
    #   - elastic
    #   - backend
    depends_on:
      - elasticsearch
    
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
  #   container_name: kibana
  #   environment:
  #     ELASTICSEARCH_HOSTS: http://elasticsearch:9200 # connect to elasticsearch
  #     ELASTICSEARCH_URL: http://elasticsearch:9200 # use in old version
  #     ELASTICSEARCH_USERNAME: kibana_system 
  #     ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD:?error} 
  #     # xpack.security.http.ssl.enabled: "false"
  #     # xpack.license.self_generated.type: trial
  #     # ELASTICSEARCH_USERNAME: elastic 
  #     # ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:?error} 
  #     # SERVER_PUBLICBASEURL: http://localhost:5602
  #   mem_limit: ${MEM_LIMIT}
  #   ports:
  #     - 5601:5601
  #   # volumes:
  #   #   - kbndata:/usr/share/kibana/data
  #   # networks:
  #   #   - elastic
  #   depends_on:
  #     - elasticsearch

volumes:
  esdata:
    driver: local
#   lstdata:
#     driver: local

# networks:
#   backend:
#     driver: bridge
#   elastic:
#     driver: bridge
